CREATE TABLE pedidos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    reserva_id BIGINT,
    detalle TEXT NOT NULL,
    fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total DOUBLE NOT NULL DEFAULT 0.0,
    estado VARCHAR(50) NOT NULL DEFAULT 'EN_PREPARACION'
);