server.port=8082
spring.application.name=pedido-service


spring.datasource.url=jdbc:mysql://localhost:3306/pedido_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=C4dpeafg**

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=update