server.port=8087

# Configuraci\u00F3n de base de datos (con el comando de creaci\u00F3n)
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD:C4dpeafg**}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# El truco: Evita que Flyway falle si la BD no existe al arrancar
spring.flyway.create-database-if-not-exist=true
spring.flyway.baseline-on-migrate=true

# Hibernate crear\u00E1 la estructura inicial
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect